chore: swap travis for github actions
unchained-capital/hermit pull request #59
Opened 2023-10-27 19:12 UTC by waldenraines

2023-10-31 13:34 UTC, waldenraines commented on .github/workflows/ci.yml
> +    runs-on: ubuntu-20.04
Thanks @robertshuford!

2023-10-31 13:39 UTC, waldenraines commented
Failing tests:

```
=================================== FAILURES ===================================
_____________________ TestQRCodeStorage.test_bits_maximum ______________________

self = <test_limits.TestQRCodeStorage object at 0x7f3160c444d0>

    def test_bits_maximum(self):
        N = 23549
        data = 1 << N
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
>       qr.add_data(data)

tests/qrcode/test_limits.py:123: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/main.py:79: in add_data
    util.optimal_data_chunks(data, minimum=optimize))
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/util.py:346: in optimal_data_chunks
    data = to_bytestring(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = <[ValueError("Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit") raised in repr()] SafeRepr object at 0x7f3160a5be50>

    def to_bytestring(data):
        """
        Convert data to a (utf-8 encoded) byte-string if it isn't a byte-string
        already.
        """
        if not isinstance(data, six.binary_type):
>           data = six.text_type(data).encode('utf-8')
E           ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/util.py:385: ValueError
_____________________ TestQRCodeStorage.test_bits_overflow _____________________

self = <test_limits.TestQRCodeStorage object at 0x7f3160b073d0>

    def test_bits_overflow(self):
        N = 23550
        data = 1 << N
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
>       qr.add_data(data)

tests/qrcode/test_limits.py:136: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/main.py:79: in add_data
    util.optimal_data_chunks(data, minimum=optimize))
/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/util.py:346: in optimal_data_chunks
    data = to_bytestring(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = <[ValueError("Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit") raised in repr()] SafeRepr object at 0x7f31609fd550>

    def to_bytestring(data):
        """
        Convert data to a (utf-8 encoded) byte-string if it isn't a byte-string
        already.
        """
        if not isinstance(data, six.binary_type):
>           data = six.text_type(data).encode('utf-8')
E           ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/qrcode/util.py:385: ValueError
=============================== warnings summary ===============================
tests/qrcode/test_displayer.py::TestDisplayQRCode::test_valid_qr_code[fixture_opensource_bitcoin_vector_0]
tests/qrcode/test_displayer.py::TestDisplayQRCode::test_valid_qr_code[fixture_opensource_bitcoin_vector_1]
  /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/_pytest/python.py:178: RuntimeWarning: coroutine 'TestDisplayQRCode.test_valid_qr_code' was never awaited
    testfunction(**testargs)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

---------- coverage: platform linux, python 3.7.17-final-0 -----------
Name                              Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------------------
hermit/config.py                     29      0     14      0   100%
hermit/errors.py                      5      0      0      0   100%
hermit/plugin.py                     11      5      6      1    41%   10-15, 9->10
hermit/qrcode/displayer.py           22      8      2      0    58%   13-14, 18-26
hermit/qrcode/format.py              40      7      8      1    83%   11, 41-46, 10->11
hermit/qrcode/reader.py              43      3     10      4    87%   47-48, 62, 27->65, 31->55, 51->31, 59->62
hermit/qrcode/utils.py                3      1      0      0    67%   5
hermit/rng.py                        58     29     12      0    50%   48-76, 93-96, 99-105, 108-109
hermit/shamir_share.py               43      2      6      0    92%   30-31
hermit/shards/interface.py          128    103     42      0    16%   24-25, 28-36, 39-49, 56-68, 75-83, 88-109, 112, 116, 120-121, 124-142, 145-163, 166-216
hermit/shards/shard.py               67      6     12      5    86%   29, 45, 55, 65, 93, 128, 28->29, 44->45, 54->55, 64->65, 92->93
hermit/shards/shard_set.py          205     78     62      7    60%   58-83, 86, 94-96, 99-100, 198-199, 205-207, 210, 226-232, 235-246, 249, 252-254, 257-269, 275-277, 285-298, 301, 304-305, 308-310, 313-318, 322, 325, 328, [33](https://github.com/unchained-capital/hermit/actions/runs/6677646473/job/18225519076#step:7:34)1-333, 57->58, 85->86, 89->exit, 132->1[34](https://github.com/unchained-capital/hermit/actions/runs/6677646473/job/18225519076#step:7:35), 197->198, 209->210, 274->275
hermit/signer/base.py                73      0     18      0   100%
hermit/signer/bitcoin_signer.py     183      0     80      0   100%
hermit/signer/echo_signer.py         11      0      0      0   100%
hermit/ui/base.py                    27     27      6      0     0%   1-40
hermit/ui/common.py                  27     27      2      0     0%   1-74
hermit/ui/main.py                    16     16      2      0     0%   1-29
hermit/ui/relocker.py                15     15      6      0     0%   1-21
hermit/ui/repl.py                    62     62     26      0     0%   1-91
hermit/ui/shards.py                  49     49      2      0     0%   1-341
hermit/ui/state.py                    8      8      0      0     0%   1-15
hermit/ui/toolbar.py                 17     17      6      0     0%   1-25
hermit/ui/wallet.py                  41     41      2      0     0%   1-203
hermit/wallet.py                     55      0     12      0   100%
-----------------------------------------------------------------------------
TOTAL                              1238    504    3[36](https://github.com/unchained-capital/hermit/actions/runs/6677646473/job/18225519076#step:7:37)     18    [59](https://github.com/unchained-capital/hermit/actions/runs/6677646473/job/18225519076#step:7:60)%

========= 2 failed, [105](https://github.com/unchained-capital/hermit/actions/runs/6677646473/job/18225519076#step:7:106) passed, 2 skipped, 2 warnings in 14.18 seconds =========
```

2023-10-31 17:42 UTC, robertshuford requested changes

2023-10-31 17:49 UTC, waldenraines commented on .travis.yml
Okay, done in 2cc53340340c4753a32095873ce7ba30972657e2.

2023-11-03 05:48 UTC, robertshuford approved these changes

2023-11-03 13:07 UTC, merged